name: news_c_kelompok4

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  barcode_widget: ^2.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  flutter_slidable: ^0.6.0
  fluttertoast: ^8.0.8
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.18.1
  line_awesome_flutter: ^2.0.0
  pdf: ^3.6.4
  printing: ^5.9.0
  responsive_sizer: ^3.2.0
  screen_brightness: ^0.2.2+1
  sensors: ^2.0.3
  shared_preferences: ^2.0.8
  sqflite: ^2.2.6
  uuid: ^3.0.6

dev_dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.4
  mobile_scanner: ^3.5.2
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo.png
    - lib/images/
    - lib/images/fotoProfil/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
